### PR TITLE
Refactor remote screen to an HTML custom element

### PR DESCRIPTION
**Pull request by mtlynch**

### CODE REVIEW

**Comment by mtlynch** [comment]
This doesn't work yet, but I want to pull the complexity of the remote screen out of the general-purpose `app.js` and `style.css`.

**Comment by djclueless** [comment]
I got it working mostly I will push the changes, it will still need some tweaking though

**Comment by djclueless** [comment]
hmm not sure how to attach the changes to this PR it created a new one.

**Comment by djclueless** [comment]
I still see issues with the Full Screen mode, cursor input from out of the screen-img area. You can either have Width:100% or Height:100% but not both. The JS I created compares the aspect ratios to choose the appropriate style.

Instead of width and height I also tried min-width: 100vw; and min-height: 100vh; with the same outcome.

The problem is we want to maintain the aspect ratio so padding is created inside the  to fill the gap.

**Comment by mtlynch** [comment]
@djclueless - Okay, I think I've got it all working now. I used your JS solution for detecting aspect ratio, but I found a way we can do it without doing such direct style manipulation in JS.

**Comment by mtlynch** [comment]
D'oh! I thought I had it. Still skew on the mouse.

**Comment by mtlynch** [comment]
Okay, I think I got it now. I realized that manipulating the class in `attributeChangedCallback` was wrong because the window size hasn't changed to fullscreen yet, so calculations are off.

**Comment by djclueless** [comment]
yup that is why I had put the setTimeout originally. I am still having issues with the padding in full screen, causes overflow. right to left. Is the padding actually required, doesn't seem like its even being used in default mode since the max width is 85% anyways?

**Comment by mtlynch** [comment]
True, we don't need padding. Removed in b9d07f2

**Comment by djclueless** [comment]
These are the images I was testing with, different resolutions, Looks good now, not seeing any issues.



300x168
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRs4T6TlarebzZRgA-qF5S5JOKcXxF9SajW7Q&usqp=CAU
document.getElementById("remote-screen-img").src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRs4T6TlarebzZRgA-qF5S5JOKcXxF9SajW7Q&usqp=CAU"
document.getElementById("remote-screen").shadowRoot..getElementById("remote-screen-img").src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRs4T6TlarebzZRgA-qF5S5JOKcXxF9SajW7Q&usqp=CAU"

750x500
https://1stwebdesigner.com/wp-content/uploads/2019/07/css-background-effects-thumb.jpg
document.getElementById("remote-screen-img").src="https://1stwebdesigner.com/wp-content/uploads/2019/07/css-background-effects-thumb.jpg"
document.getElementById("remote-screen").shadowRoot.getElementById("remote-screen-img").src="https://1stwebdesigner.com/wp-content/uploads/2019/07/css-background-effects-thumb.jpg"

960x539
https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569_960_720.jpg
document.getElementById("remote-screen-img").src="https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569_960_720.jpg"
document.getElementById("remote-screen").shadowRoot.getElementById("remote-screen-img").src="https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569_960_720.jpg"

1080x1920 (portrait)
https://wallpapercave.com/wp/wp2419342.jpg
document.getElementById("remote-screen-img").src="https://wallpapercave.com/wp/wp2419342.jpg"
document.getElementById("remote-screen").shadowRoot.getElementById("remote-screen-img").src="https://wallpapercave.com/wp/wp2419342.jpg"

1280x720
https://i.pinimg.com/originals/a5/f2/33/a5f233141607463c4feb2458db9a77cc.jpg
document.getElementById("remote-screen-img").src="https://i.pinimg.com/originals/a5/f2/33/a5f233141607463c4feb2458db9a77cc.jpg"
document.getElementById("remote-screen").shadowRoot.getElementById("remote-screen-img").src="https://i.pinimg.com/originals/a5/f2/33/a5f233141607463c4feb2458db9a77cc.jpg"

1357x763
https://www.vamosrayos.com/b/2020/01/cool-hd-background-pics-photos-1080p-for-photoshop.jpg
document.getElementById("remote-screen-img").src="https://www.vamosrayos.com/b/2020/01/cool-hd-background-pics-photos-1080p-for-photoshop.jpg"
document.getElementById("remote-screen").shadowRoot.getElementById("remote-screen-img").src="https://www.vamosrayos.com/b/2020/01/cool-hd-background-pics-photos-1080p-for-photoshop.jpg"

1920x1200
https://lazaworx.com/lazaworx/wp-content/uploads/2012/03/ScreenResolutionsBg.png
document.getElementById("remote-screen-img").src="https://lazaworx.com/lazaworx/wp-content/uploads/2012/03/ScreenResolutionsBg.png"
document.getElementById("remote-screen").shadowRoot.getElementById("remote-screen-img").src="https://lazaworx.com/lazaworx/wp-content/uploads/2012/03/ScreenResolutionsBg.png"

1200x675
https://cdn2.hubspot.net/hubfs/3350762/Top%20Cybersecurity%20Zoom%20Backgrounds-4.png
document.getElementById("remote-screen-img").src="https://cdn2.hubspot.net/hubfs/3350762/Top%20Cybersecurity%20Zoom%20Backgrounds-4.png"
document.getElementById("remote-screen").shadowRoot.getElementById("remote-screen-img").src="https://cdn2.hubspot.net/hubfs/3350762/Top%20Cybersecurity%20Zoom%20Backgrounds-4.png"

5110x2880
https://wallpaperaccess.com/full/752775.jpg
document.getElementById("remote-screen-img").src="https://wallpaperaccess.com/full/752775.jpg"
document.getElementById("remote-screen").shadowRoot.getElementById("remote-screen-img").src="https://wallpaperaccess.com/full/752775.jpg"

**Comment by mtlynch** [comment]
Awesome, thanks for your help! I was doing something similar with these: https://imgur.com/a/7X4Y31u

**Pull request merged**
