### PR TITLE
Refactor update module and add unit tests

### PR DESCRIPTION
**Pull request by mtlynch**
This refactors the update module to make it simpler, more testable, and better documented. This *should* be a pure refactoring that preserves all existing behavior.

The update component is important because failed updates are an especially poor user experience. There were previously no automated tests because of the difficulty of testing update logic, but I've broken up the module to mock out dependencies that were obstructing testing.

I'm planning to simplify the logic in a future PR (see #597), but I wanted to first create tests to lock in the existing behavior.

---
This change is [Reviewable](https://reviewable.io/reviews/mtlynch/tinypilot/636)

### CODE REVIEW

**Comment by jotaen** [comment]
(fyi) I don’t get around to it today anymore, but look into it tomorrow.

**Review by jotaen — APPROVED** [review]
Just some smaller suggestions, but looks good otherwise. Have also tested it out to double-check.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mtlynch/tinypilot/636#-:-MYA7MxM20ZE80ATaQ0t:b-lh675u)* status: all files reviewed, 2 unresolved discussions (waiting on @mtlynch)

___
*[app/update_result_reader_test.py, line 11 at r1](https://reviewable.io/reviews/mtlynch/tinypilot/636#-MYA4jeoCJQDsWWtAMGO:-MYA4jeoCJQDsWWtAMGP:bxmg0nx) ([raw file](https://github.com/mtlynch/tinypilot/blob/6b3d2e866f285e794d002cd3e4bfee7150ced7c4/app/update_result_reader_test.py#L11)):*
> ```Python
> 
> 
> class UpdateResultReaderTest(unittest.TestCase):
> ```

We could add a test for the case that the result file timestamp is *ahead* of time, e.g. say it’s 00:03:00 on the system, but there is a result file for 01:05:00. This could happen due to a NTP sync in between (e.g. a daylight saving switch or just clock skew). Unlikely, but nice anyway to prove that we are robust against it.
___
*[app/update_result_reader_test.py, line 60 at r1](https://reviewable.io/reviews/mtlynch/tinypilot/636#-MYA6h2X--YF0yDn3-23:-MYA6h2X--YF0yDn3-24:b-wp9roa) ([raw file](https://github.com/mtlynch/tinypilot/blob/6b3d2e866f285e794d002cd3e4bfee7150ced7c4/app/update_result_reader_test.py#L60)):*
> ```Python
>             """)
>         ]
>         mock_now.return_value = datetime.datetime(2021,
> ```

I think named arguments could make the constructor a bit better to read (`year=2021,`)

**Comment by jotaen** [comment]
One general consideration that came to my mind, only loosely related to this PR, however: we are currently using functions to trigger procedures, which forces us to use mocks and therefore whitebox testing. An alternative could be to use classes and dependency injection. This could also come in handy for injecting “mock” dependencies for local development. On the other hand it would make the whole setup more verbose, so not sure currently whether it’s worth it. Just wanted to put it out there as a thought.

**Comment by mtlynch** [comment]
>One general consideration that came to my mind, only loosely related to this PR, however: we are currently using functions to trigger procedures, which forces us to use mocks and therefore whitebox testing. An alternative could be to use classes and dependency injection. This could also come in handy for injecting “mock” dependencies for local development. On the other hand it would make the whole setup more verbose, so not sure currently whether it’s worth it. Just wanted to put it out there as a thought.

Yeah, I used to be very religious about unit test purity. I avoided the `mock` package and instead always passed in dependencies as parameters to the constructor. I hated the idea of `mock` because it broke the abstraction and allowed the tests to "know" implementation details about the system under test that aren't part of its public interface.

But I eventually felt like it made everything more complex without much meaningful benefit. Like 4 years ago, I would have written this `update_result_reader` as a class with a `self._globber` member instead of calling `glob.glob` directly, but it adds a level of indirection. If you have experience with Python, you recognize `glob.glob`, whereas you can't recognize `self._globber` without going and tracing what it actually points to.

If something naturally is going to be a class and it depends on another custom class, that's a case where I'd want to accept a parameter instead of hardcoding to a particular implementation. It's just cleaner to test it that way as opposed to trying to sneak in a test implementation with mocks. But since going to "the dark side" of less strict dependencies, I haven't really seen a downside.

I'm definitely open to revisit it if there are downsides I'm missing.

**Review by mtlynch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mtlynch/tinypilot/636)* status: all files reviewed, 2 unresolved discussions (waiting on @jotaen)

___
*[app/update_result_reader_test.py, line 11 at r1](https://reviewable.io/reviews/mtlynch/tinypilot/636#-MYA4jeoCJQDsWWtAMGO:-MYBvzdu4H8Lir6u3I78:b-fd7dxa) ([raw file](https://github.com/mtlynch/tinypilot/blob/6b3d2e866f285e794d002cd3e4bfee7150ced7c4/app/update_result_reader_test.py#L11)):*
<details><summary><i>Previously, jotaen (Jan Heuermann) wrote…</i></summary><blockquote>

We could add a test for the case that the result file timestamp is *ahead* of time, e.g. say it’s 00:03:00 on the system, but there is a result file for 01:05:00. This could happen due to a NTP sync in between (e.g. a daylight saving switch or just clock skew). Unlikely, but nice anyway to prove that we are robust against it.
</blockquote></details>

Oh, good point. Added!

NTP could cause this. I don't think daylight saving could because we track timestamps in UTC, which doesn't change due to daylight saving time.
___
*[app/update_result_reader_test.py, line 60 at r1](https://reviewable.io/reviews/mtlynch/tinypilot/636#-MYA6h2X--YF0yDn3-23:-MYBvO7O0FOMRPKhZ3ch:b-sm9ndk) ([raw file](https://github.com/mtlynch/tinypilot/blob/6b3d2e866f285e794d002cd3e4bfee7150ced7c4/app/update_result_reader_test.py#L60)):*
<details><summary><i>Previously, jotaen (Jan Heuermann) wrote…</i></summary><blockquote>

I think named arguments could make the constructor a bit better to read (`year=2021,`)
</blockquote></details>

Good idea. Added!

**Pull request merged**
