### PR TITLE
Add sub-menus to drop-down

### PR DESCRIPTION
**Pull request by djclueless**
This adds sub-menus to the existing drop-down on the nav bar.

Example HTML

```html
<li class="dropdown">
  <a>Commands</a>
  <ul>
    <li>
      <a id="paste-btn">Paste</a>
      <li class="dropdown-divider"></li>
      <li>
        <a>Screen<span class="caret"></a>
        <ul>
            <li class="dropdown-item"><a href="#">Default</a></li>
            <li class="dropdown-item"><a href="#">Fill</a></li>
            <li class="dropdown-item"><a href="#">Fullscreen</a></li>
        </ul>
      </li>
      <li>
        <a>Cursor<span class="caret"></span></a>
        <ul>
            <li class="dropdown-item"><a href="#">Default</a></li>
            <li class="dropdown-item"><a href="#">Crosshair</a></li>
            <li class="dropdown-item"><a href="#">Dot</a></li>
            <li class="dropdown-item"><a href="#">None</a></li>
            <li class="dropdown-item"><a href="#">Cell</a></li>
            <li class="dropdown-item"><a href="#">Pointer</a></li>
        </ul>
      </li>
  </ul>
</li>
```

### CODE REVIEW

**Comment by mtlynch** [comment]
Nice, thanks!

I'm seeing buggy rendering on Chrome 85.

improper-menu

For this one, can we actually pull in the cursor changes as part of the same PR? It's easier to understand CSS rules if we introduce the HTML that uses it at the same time.

**Comment by djclueless** [comment]
That might be a cache issue for the drop down. I can in add the cursor options to this if it's easier.

**Comment by mtlynch** [comment]
It doesn't seem to be caching. I'm doing hard refreshes and still see it. I tried in an incognito window too and saw the same. I tried manually restarting the server and there was no difference.

tinypilot-menus

>I can in add the cursor options to this if it's easier.

Yeah, that would be great!

**Comment by mtlynch** [comment]
It looks like you merged from `master`, so unrelated changes are getting pulled into this PR. You can do `git reflog` and check out a point before the merge, then force push to Github to drop the merge.

Alternatively, if you do `git rebase master` it should unclutter the PR.

[Rebasing](https://git-scm.com/docs/git-rebase) is a pain at first, but once you get the hang of it, it's extremely useful.

**Comment by djclueless** [comment]
Yeah so I am trashing this one, I will make a new one with the cursor options all in one.

**Pull request closed without merging**
