### PR TITLE
Mobile UI Fix

### LINKED ISSUE #263: Keyboard history panel overflows on mobile
## Description

The keyboard history panel seems to overflow the view on mobile.

I'm pretty sure this is related to the key cards using fixed-width CSS. We should adjust it for CSS so that they flow in a more natural way on smaller viewports.

## What's the behavior that you expect?

Keyboard history panel stays within the width of the navbar.

## What's happening instead?

Keyboard history panel width is <= navbar width.

## What are the steps to reproduce this behavior?

1. View TinyPilot on an Android mobile device

## Screenshots

image

## Logs

N/A

### PR DESCRIPTION
**Pull request by djclueless**
Fixes #263

Adjust viewport scale.

### CODE REVIEW

**Comment by mtlynch** [comment]
Could we split these changes into separate PRs? Some of them I think are the right changes, but some of them I think we need to rethink a little bit.

>Fix modifier key panel on mobile small screens

>Fix key stroke history on mobile screens

These are good, but it doesn't seem to work for me:

image

>Resize Logo on smaller screens

I'm okay with resizing a little bit, but the current implementation hides it entirely when the screen is too narrow. I'd rather have it be more like the TinyPilot website:

image

>Hide Connection label on small screens

This seems reasonable.

**Comment by djclueless** [comment]
Hey sorry been busy with work. I am going to rethink the best way to fix this. If we can just do a same site fixed width so it all fits, although it will be smaller text, the remote-screen should still be the correct size.

 I do not know about modifying the navbar to matching the Tiny Pilot site, that seems like a UI overhaul lol

**Comment by mtlynch** [comment]
Yeah, the navbar is going to be a little bit more of an effort, but it shouldn't be too bad. This is basically what I'm aiming for:

https://medium.com/@adamwojnicki/lets-build-a-simple-responsive-navigation-bar-with-html-css-and-a-little-bit-of-vanilla-js-5abba28da32e

**Comment by djclueless** [comment]
That navbar seems simple enough, only issue would be the nested menu for the cursors.

What do you want to do with this PR? Is the viewport fix sufficient for now, or are we scraping this and just wait until the navbar gets redone?

**Comment by mtlynch** [comment]
Why are we restrictive with the viewport? 

Could it just be the standard?

```html
content="width=device-width, initial-scale=1"
```

**Comment by djclueless** [comment]
I restricted the viewport because android zooms into the input on focus. I do not want to have to zoom or change the view every time I want to type something on mobile, I just want the keyboard to open up at its current location.

To fix the UI we would need to do `initial-scale=0.4"`   0.5 has over flow for me, and 1 causes the navbar issue show in the screen capture. #263 


https://stackoverflow.com/questions/7073396/disable-zoom-on-input-focus-in-android-webpage

**Comment by mtlynch** [comment]
I can't reproduce the difference in behavior. Both `initial-scale=0.4` and `initial-scale=1` seem to do the same for me. What should appear differently?

**Comment by djclueless** [comment]
This is on a moto G7 (424x891)



**1.0 (scalable)**
image



**1.0 (not scalable)**
image



**0.4 (not scalable)**
image

**Comment by mtlynch** [comment]
I think we should simplify the existing tag to `content="width=device-width, initial-scale=1"`. From what I'm reading `user-scalable=no` creates issues with accessibility for users who want to zoom. If the goal is to fix experience on mobile, I think we need to adjust those elements so that they don't overflow the viewport.

**Pull request closed without merging**
