### PR TITLE
Add fullscreen support

### LINKED ISSUE #106: Add support for "full screen" mode
This is more of an enhancement then a "issue".

It would be great to have an option to full-screen the HDMI stream. Some of the installers makes the display really small and not really visible (alpine linux being one of them...)

### PR DESCRIPTION
**Pull request by raiju**
Fixes #106

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
Cool!

I tested it out, but it looks like it only works if the two computers have identical aspect ratios. My target computer is 1366x768, and my desktop is 3440x1440.

When I view the remote computer in non-fullscreen, it looks like this:

image

In fullscreen, the bottom ~20% of the screen is chopped off:

image

Is there a way we can add black edges to the top or sides of the DOM element to match the client's aspect ratio to the remote machine?

**Comment by raiju** [comment]
Will look into it. That's the risk of testing on a combo with the exact same ratios 😅

**Comment by mtlynch** [comment]
@raiju - To avoid duplicating effort, there's a working implementation of fullscreen in #196.

**Comment by mtlynch** [comment]
Fullscreen is merged in as of #219.

**Pull request closed without merging**
