### PR TITLE
Use title case and proper headlines in overlays

### PR DESCRIPTION
**Pull request by jotaen**
Quick boy scout refactoring, I stumbled across these two places and noticed they weren’t inline with the style guide.

### CODE REVIEW

**Review by mtlynch — APPROVED** [review]
LGTM, but I'm going to leave this open for Circle to investigate why these builds are not running.

**Comment by jotaen** [comment]
Is there any news from Circle yet? It happened again that the builds are not kicking off (https://github.com/mtlynch/tinypilot/pull/676) 🤔 . It didn’t occur in the Pro repo though, but not sure whether it happens consistently.

**Comment by mtlynch** [comment]
No response yet. We don't have a premium support plan with them, so they don't have an SLA on support requests. Their target SLO for standard accounts is 3 days, but it's been 4 days at this point with no response. Hopefully we get an answer from them soon.

**Comment by jotaen** [comment]
Yay Circle 🎉

**Pull request merged**
