### PR TITLE
Remove deprecated functions

### PR DESCRIPTION
**Pull request by jotaen**
Complete the migration of the API responses:

- Rename `success2`→`success`
- Remove deprecated functions
- Keep a proxy version of `success2` and `error2`, otherwise it will break Pro upon merging.

### CODE REVIEW

**Review by mtlynch — APPROVED** [review]
LGTM, thanks!

**Comment by jotaen** [comment]
@mtlynch could you merge into Pro one last time, please?

**Comment by mtlynch** [comment]
@jotaen - Sure, no problem. Merged!

**Comment by jotaen** [comment]
Cool, thanks! (And sorry for having made you do this that often 😸 )

**Pull request merged**
